# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('is_send', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_message',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messages.Report'),
        ),
    ]
