# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_auto_20180224_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_id',
        ),
        migrations.AddField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
