# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0003_auto_20180224_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='report_id',
            new_name='report',
        ),
    ]
